package auth

const (
	key = `-----BEGIN EC PARAMETERS-----
BgUrgQQAIg==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDCeSCLp7ubA5yGYuKGdT2BH4/7jKF8bDzgHZ5NZezYXJvOZGClbpTeO
u1YapitzBsWgBwYFK4EEACKhZANiAATxyl1emU76L/SuSgb+/wcK+0F1RfnV1bIi
BEo9TgcNZrS2Cg2BtVDU5lU/JWq2MD6dCw/1AnHsmSBVAkErT/EsFw4QfC4WfwH4
uszYCgleBhJVOlq1344658/k8wQC9wM=
-----END EC PRIVATE KEY-----`

	cert = `-----BEGIN CERTIFICATE-----
MIIBiTCCAQ8CCQCPkJHffydgxDAKBggqhkjOPQQDAjAuMQswCQYDVQQGEwJVUzEL
MAkGA1UECAwCTkMxEjAQBgNVBAcMCUNoYXJsb3R0ZTAeFw0xODExMTgyMjAyMjla
Fw0yODExMTUyMjAyMjlaMC4xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOQzESMBAG
A1UEBwwJQ2hhcmxvdHRlMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8cpdXplO+i/0
rkoG/v8HCvtBdUX51dWyIgRKPU4HDWa0tgoNgbVQ1OZVPyVqtjA+nQsP9QJx7Jkg
VQJBK0/xLBcOEHwuFn8B+LrM2AoJXgYSVTpatd+OOufP5PMEAvcDMAoGCCqGSM49
BAMCA2gAMGUCMEV0jl2NWMYq6ZKn0WJetv/UwOjH+/qrxwdZgC/Uy+EvSKpPX3jf
osePYHM6WQ6qGQIxAOEylLJaThdQQEZYYBJRwE5j5YlRHFCZCJixY1OAUK04cKLF
kiXodcCYhpLO8vqcRg==
-----END CERTIFICATE-----`
)
